<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Permisos.aspx.cs" Inherits="GlobalLogistics.Permisos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            Permisos<br />
            <br />
        </div>
        <asp:GridView ID="grdPermisos" runat="server" AutoGenerateSelectButton="True" OnSelectedIndexChanged="grdPermisos_SelectedIndexChanged">
        </asp:GridView>
        <p>
            <asp:Button ID="btnBorrarSeleccion" runat="server" OnClick="btnBorrarSeleccion_Click" Text="Borrar Seleccion" />
        </p>
        <p>
            Agregar Permiso</p>
        <p>
            Permiso<asp:DropDownList ID="ddlPermisos" runat="server">
            </asp:DropDownList>
        </p>
        <p>
            Nombre<asp:TextBox ID="txtNombre" runat="server"></asp:TextBox>
        </p>
        <p>
            <asp:Button ID="btnGuardar" runat="server" OnClick="btnGuardar_Click" Text="Guardar Patente" />
            <asp:Button ID="btnCrearFamilia" runat="server" OnClick="btnCrearFamilia_Click" Text="Crear Familia" />
            <asp:Button ID="btnVolver" runat="server" OnClick="btnVolver_Click" Text="Volver" />
        </p>
        <asp:GridView ID="grdFamilia" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnRowDeleted="grdFamilia_RowDeleted" OnSelectedIndexChanged="grdFamilia_SelectedIndexChanged">
        </asp:GridView>
        <asp:Button ID="gtnGuardarFamilia" runat="server" OnClick="gtnGuardarFamilia_Click" Text="Guardar Familia" />
    </form>
</body>
</html>
