//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalLogistics.WSRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSRef.WSGlobalLogisticsSoap")]
    public interface WSGlobalLogisticsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerStock", ReplyAction="*")]
        int ObtenerStock(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerStock", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ObtenerStockAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSGlobalLogisticsSoapChannel : GlobalLogistics.WSRef.WSGlobalLogisticsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSGlobalLogisticsSoapClient : System.ServiceModel.ClientBase<GlobalLogistics.WSRef.WSGlobalLogisticsSoap>, GlobalLogistics.WSRef.WSGlobalLogisticsSoap {
        
        public WSGlobalLogisticsSoapClient() {
        }
        
        public WSGlobalLogisticsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSGlobalLogisticsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSGlobalLogisticsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSGlobalLogisticsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ObtenerStock(int id) {
            return base.Channel.ObtenerStock(id);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerStockAsync(int id) {
            return base.Channel.ObtenerStockAsync(id);
        }
    }
}
